#Global constants
SNAKE_NUMBER = 5
FOOD_NUMBER = 5
GAME_LABEL = "WANNA PLAY WITH SNAKES?"
SCORE_LABEL = "SCORES:"

#Terminal constants
GAME_ROW_COUNT = 30
GAME_COL_COUNT = 90
SCORE_ROW_COUNT = 30
SCORE_COL_COUNT = 30
WIN_ROW_COUNT = GAME_ROW_COUNT
WIN_COL_COUNT = GAME_COL_COUNT + SCORE_COL_COUNT + 4

#Pygame connstants
FPS = 10
RADIUS = 10
P_GAME_ROW_COUNT = 40
P_GAME_COL_COUNT = 80
P_SCORE_ROW_COUNT = 40
P_SCORE_COL_COUNT = 20
P_WIN_ROW_COUNT = P_GAME_ROW_COUNT * RADIUS
P_WIN_COL_COUNT = (P_GAME_COL_COUNT + P_SCORE_COL_COUNT) * RADIUS
