#Global constants
SNAKE_NUMBER = 5
FOOD_NUMBER = 5
GAME_LABEL = "WANNA PLAY WITH SNAKES?"
SCORE_LABEL = "SCORES:"

#Terminal constants
GAME_ROW_COUNT = 30
GAME_COL_COUNT = 90
SCORE_ROW_COUNT = 30
SCORE_COL_COUNT = 30
WIN_ROW_COUNT = GAME_ROW_COUNT + SCORE_ROW_COUNT
WIN_COL_COUNT = GAME_COL_COUNT + SCORE_COL_COUNT + 4


#Pygame connstants
FPS = 10
RADIUS = 10
WIN_WIDTH = WIN_COL_COUNT * RADIUS
WIN_HEIGHT = WIN_ROW_COUNT * RADIUS
GAME_WIN_WIDTH = GAME_COL_COUNT * RADIUS
GAME_WIN_HEIGHT = GAME_ROW_COUNT * RADIUS
SCORE_WIN_WIDTH = SCORE_COL_COUNT * RADIUS
SCORE_WIN_HEIGHT = SCORE_ROW_COUNT * RADIUS 